version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
    command: sleep infinity

  dev-db:
    restart: always
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=cb-dev
      - POSTGRES_USER=cb-dev
      - POSTGRES_DB=cb-dev
    volumes:
      - dev-db:/var/lib/postgresql/data

volumes:
  dev-db: