name: LicenseFinder CI

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - "**"

jobs:
  test:
    name: Check dependencies licenses
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: Install cargo
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install task
        run:
          npm install -g @go-task/cli
      
      - name: Install wasm-pack
        run:
          cargo install wasm-pack

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - name: Install LicenseFinder
        run: gem install license_finder
      
      - name: Building client
        run: task build:client

      - name: Run LicenseFinder
        run: license_finder --decisions_file ./.github/dependency_decisions.yml

      - name: Run LicenseFinder (client)
        run: cd client && license_finder --decisions_file ../.github/dependency_decisions.yml
