name: Test CI

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Run Tests
        run: |
         mkdir client/build
         touch client/build/dummyfile
         go test ./...
